sudo: required
services:
    - docker


before_install:
  - docker build -t bryangranadilla911/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run bryangranadilla911/react-test npm test -- --coverage


after_success:
  - docker build -t bryangranadilla911/multi-nginx ./nginx
  - docker build -t bryangranadilla911/multi-client ./client
  - docker build -t bryangranadilla911/multi-server ./server
  - docker build -t bryangranadilla911/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bryangranadilla911/multi-nginx
  - docker push bryangranadilla911/multi-client
  - docker push bryangranadilla911/multi-server
  - docker push ryangranadilla911/multi-worker